require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'


Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']
